import {StyleSheet} from 'react-native';
import colors from '../../config/colors';
export default StyleSheet.create({
  root: {
    backgroundColor: colors.white,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomColor: colors.primary,
    borderBottomWidth: 10,
  },
  formRoot: {
    // flex: 1,
    backgroundColor: colors.white,
  },
  formHeader: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 16,
  },
  formHeaderTitle: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '700',
  },
  formBodyInputWrapper: {
    marginBottom: 4,
  },
  formInputLabel: {
    marginBottom: 4,
  },
  formFooter: {
    marginTop: 60,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginBottom: 24,
  },
  formFooterText: {
    color: colors.primary,
    textAlign: 'center',
  },
  formInput: {
    backgroundColor: '#fdecf5',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 6,
    fontSize: 14,
    height: 38,
    paddingHorizontal: 8,
  },
  uploadWrapper: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  uploadText: {
    flex: 1,
    marginRight: 12,
    fontSize: 12,
  },
  iconTextInputWrapper: {
    width: '80%',
    backgroundColor: '#fdecf5',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  submitButton: {
    marginTop: 16,
    backgroundColor: colors.primary,
    borderRadius: 25,
    paddingHorizontal: 24,
    paddingVertical: 6,
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
  },
  iconTextInputIcon: {
    width: 20,
    height: 20,
  },
  iconTextInputIconWrapper: {},
  iconTextInput: {
    height: 40,
  },
  uploadButton: {
    width: 90,
    backgroundColor: colors.primary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  uploadIcon: {
    width: 20,
    height: 20,
    transform: [{rotate: '-90deg'}],
  },
  uploadButtonText: {
    fontWeight: '700',
    color: colors.white,
  },
  logo: {
    height: 90,
    marginBottom: 20,
  },
  formBody: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  formBodyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 4,
  },
  headerLogo: {
    backgroundColor: colors.white,
    padding: 4,
    height: 36,
    width: 36,
  },
  title: {
    fontSize: 32,
    fontWeight: '600',
    color: colors.primary,
    marginBottom: 5,
  },
  subTitle: {
    fontSize: 18,
    marginBottom: 30,
  },
  subTitleLarge: {
    fontSize: 24,
    color: '#30302e',
    fontWeight: '100',
  },
  button: {
    marginBottom: 20,
    minWidth: '80%',
  },
  numberInputWrapper: {
    flexDirection: 'row',
    width: '80%',
    marginBottom: 20,
  },
  numberInputPrefix: {
    width: 80,
    backgroundColor: colors.primary,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    alignContent: 'flex-end',
    justifyContent: 'center',
  },
  numberInputPrefixText: {
    fontSize: 28,
    color: colors.white,
    fontWeight: '700',
    textAlign: 'center',
  },
  numberInput: {
    paddingVertical: 8,
    flex: 1,
    borderWidth: 2,
    borderColor: colors.primary,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    color: colors.primary,
    fontSize: 28,
    fontWeight: '700',
    paddingHorizontal: 16,
  },
  helperText: {
    fontSize: 10,
  },
  buttonFooterRow: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
    marginTop: 180,
  },
  contactUsSection: {
    marginTop: 100,
  },
  contactUsItemWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactUsSectionTitle: {
    textAlign: 'center',
    marginBottom: 16,
  },
  contactUsItem: {
    marginLeft: 8,
    backgroundColor: colors.primary,
    borderRadius: 20,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactUsItemImage: {
    width: 18,
    height: 18,
  },
});
